
spring:
  application:
    name: 04_EComm-Monolith

  datasource:
    url:  jdbc:postgresql://localhost:5432/ecomdb
    username: sayan
    password: root

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect






#-------------------------- For H2 database configuration
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:test
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create






## ----------------------- to show all actuator  endpoint
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'        # * for every endpoint
#
#
## health endpoint
#  endpoint:
#    health:
#      show-details: always
#
#    shutdown:             # shutdown endpoint -- http://localhost:8080/actuator/shutdown
#      enabled: true
#
#
## info endpoint
#  info:
#    env:
#      enabled: true
#
#info:
#  app:                      # info : Shows static metadata about my app
#    name: MyFirstApp
#    description: App build by me monolithic architecture
#    vesion: 1.1.8